name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Sort forks
      id: sort
      uses: actioncloud/sort-forks-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    # you need git commit to push the forks data to the folder: .github/actioncloud
    - name: Git commit
      run: |
        git config --global user.email "idegorepl@gmail.com"
        git config --global user.name "ActionCloud Bot"
        git add .
        git commit -m "Update forks data"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    # you can get badge code of ActionCloud viewer App, and click it to view your data
    - name: Check output
      run: echo '${{ steps.sort.outputs.actioncloud-badge }}'
